### ISSUE TITLE
Building does not work on OS X

### ISSUE THREAD

**Issue by mebsim** [nu-dev/nu#15]
Tried your blog thing, got 6 errors while getting the dependencies and then when building (obviously the building would not work unless you got the dependencies).

**Comment by mebsim** [comment]
Sorry never mind about the dependencies error, that was just something else, but the building would not work

> gcc -c -o util.o src/util.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Lhoedown/ -l:libhoedown.a -Llibnucommon -lnucommon -Wall -pedantic -static -Werror
> clang: error: -l:libhoedown.a: 'linker' input unused
> clang: error: -lnucommon: 'linker' input unused
> make: **\* [util.o] Error 1

**Comment by ohnx** [comment]
ah, that's on a mac. I'll look into fixing it.

**Comment by mebsim** [comment]
Thanks

**Comment by mebsim** [comment]
I'll look myself into what could be causing it. I'll also double check on linux if you want.

**Comment by ohnx** [comment]
the issue is just the compiler flags.

**Comment by ohnx** [comment]
@mebsim I've added you as a collaborator, try to see if you can get nu up and running, and then see if you can write some documentation ;)

**Comment by mebsim** [comment]
Looking through your code, I might have gotten lost 50 times looking for certain bits of code.

**Comment by ohnx** [comment]
@mebsim the CI says that this should work now.

Try downloading the latest source and try again?

**Comment by mebsim** [comment]
After 'make' does not work

**Comment by mebsim** [comment]
cc -c -o util.o src/util.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror
cc -c -o pageList.o src/pageList.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror
cc -c -o post.o src/post.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror
cc -c -o unvo.o src/unvo.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror
cc -c -o kg.o src/kg.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror
cc -c -o nu.o src/nu.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror
cc -c -o cmds.o src/cmds.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror
cc -c -o strlist.o src/strlist.c -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror
cc -o nu util.o pageList.o post.o unvo.o kg.o nu.o cmds.o strlist.o -g -I include/ -I hoedown/src/ -I libnucommon/ -Wall -pedantic -static -Werror -Lhoedown/ -l:libhoedown.a -Llibnucommon -lnucommon
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [nu] Error 1

**Comment by mebsim** [comment]
That's a bit more than last time.

**Comment by ohnx** [comment]
Hmm...

I don't have a mac on me right now, so I'll check why that isn't working in ~1 week.

**Comment by mebsim** [comment]
I'll look into this further, but I'm still getting around understanding your code.

**Comment by ohnx** [comment]
ok issue resolved.

problem was with mac os x not liking `-static` flag. removed it, and now it works.
