### ISSUE TITLE
check if file is getting overwritten

### ISSUE THREAD

**Issue by ohnx** [nu-dev/nu#3]
like when i replace certain characters with `-` i don't check if the file with that case already exists.

**Comment by ohnx** [comment]
hmm how could this be done?

only ideas i have so far is `n^2` algorithm: keep a list of "checked" items (output filenames?), loop through main list and check if that element is in the "checked" items already, if it is throw an error

**Comment by mebsim** [comment]
Try to find a more efficient way of doing this, having it look through that many files is quite inefficient
